# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: .
      network: none
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kt.com
      PGADMIN_DEFAULT_PASSWORD: password
  # pgbackups:
  #   container_name: Backup
  #   image: prodrigestivill/postgres-backup-local
  #   restart: always
  #   volumes:
  #     - ./backup:/backups
  #   links:
  #     - db:db
  #   depends_on:
  #     - db
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_DB=db 
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=pass
  #     - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
  #     - SCHEDULE=@every 0h15m00s
  #     - BACKUP_KEEP_DAYS=7
  #     - BACKUP_KEEP_WEEKS=4
  #     - BACKUP_KEEP_MONTHS=6
  #     - HEALTHCHECK_PORT=81